### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Spriithy** [cznic/virtual#4]
Hey! I've come across your project :) it looks very interesting but it lacks some obvious documentation. Would you mind adding some brief guidelines towards helping me for generating code to execute on your VM ?

**Comment by cznic** [comment]
The loader of this VM consumes [IR](https://github.com/cznic/ir), which is [documented](http://godoc.org/github.com/cznic/ir). Once you have the IR, you need to [verify](http://godoc.org/github.com/cznic/ir#FunctionDefinition.Verify) and [link](http://godoc.org/github.com/cznic/ir#LinkMain) it. The result has to be [loaded](http://godoc.org/github.com/cznic/virtual#LoadMain), then the resulting binary can be [executed](http://godoc.org/github.com/cznic/virtual#Exec).

There are plans for object and binary file formats, but they're not yet implememted. But all the objects should work well with [gob](https://golang.org/pkg/encoding/gob/) if you need persistence.

It would be wonderful if you'd perhaps want to take notes on your progress and add them to the project documentation. I'll try to help you.

**Comment by cznic** [comment]
@Spriithy I hope I haven't disappointed/discouraged you. Don't hesitate to ask questions. Within my limited free time I'll try to provide feedback and support.

**Comment by Spriithy** [comment]
Hey there! I am leaving for a 3-week vacation and won't have much time to code I believe. However, what I first intended with "documentation" is far from just what `go doc` can produce :) I think you need to write some consistent doc about your program. (execution path, expected inputs, program structure).

The most important thing would be a guide to code generation for your VM. Because even though I found the Opcodes in `cpu.go`, it is not handy at all :)

**Comment by cznic** [comment]
You do not generate opcodes of the virtual CPU. Those are not documented and are an implementation detail subject to change. You need to generate the documented, execution target independent IR and link it, both using the the IR package. The virtual package can then load the linked IR and produce the "binary", containing the virtual CPU instructions which package virtual can the also execute.

I'll be still one more week away when you return from yours vacation, so have a nice time wherever you go and let's continue the discussion in September ;-)

**Comment by Spriithy** [comment]
Then you need to provide more documentation for your `IR` repository :D Because there is no way to work with it easily without reading all the code base haha.

**Comment by cznic** [comment]
I'm more than willing to improve the docs. When you'll be ready, let's iterate by you providing a question and me filling the answer into the documentation. Repeat until everything is clear for you, ok?

Anyway, every IR {object,value,operation } _is_ documented already. Perhaps some overview is missing explaining the high-level concepts.

**Comment by Spriithy** [comment]
Hey I'm back. I am quite overwhelmed at work right now. I'll file some issues in `IR` soon.

**Comment by cznic** [comment]
Nice, looking forward that.
